spring.application.name=MentalHealthBackend
spring.datasource.url=jdbc:mysql://localhost:3306/mental_health_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Klu@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true